name: Daily Job Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # codziennie o 8:00 CET
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.csv
          git commit -m "Add new offers [$(date +'%Y-%m-%d')]" || echo "No changes to commit"
          git push
